INSERT INTO shop_items (name, category, price, currency_type, shop_area, purchase_limit, description, stock) VALUES
('Linh Quang Vạn Thọ Lư (Lư Hương Đồng Thau)', 'Trấn vật di động', 4500, 'CONG_DUC', 'Hiếm', '01 chiếc / người',
 'Lư hương nhỏ bằng đồng thau cầm tay, khi lắc phát ra tiếng leng keng và tỏa khói vàng ấm áp. Cầm lư hương đi lại tác dụng lên toàn bộ đồng đội đi trong bán kính 3m xung quanh bạn, giúp liên tục hồi 3% Máu/giây (giảm 1 tag trạng thái đang gánh - tối đa 4 người) kéo dài trong 8 cmt. Tương thích Dị sự: Vừa di chuyển vừa trị thương cho đội hình ở Dị sự cấp Hoàng và Phỉ. ⚠️ Tác dụng phụ / Lưu ý: Khói vàng phát sáng rất rõ trong đêm, tựa như một ngọn hải đăng thu hút sự chú ý của Mọi loại Quỷ.', 99),
('Tụ Tinh Hồ Lô (Bầu Khô Sơn Đỏ)', 'Trang bị lưng', 3200, 'HUA_TIEN', 'Hiếm', '01 chiếc / người',
 'Trái bầu khô sơn đỏ đeo sau lưng, có khả năng tự động hút bớt tà khí xung quanh chủ nhân. Đeo sau lưng tác dụng lên Bản thân, giúp hấp thụ và triệt tiêu các trạng thái Giảm Tốc / Yếu Ớt do Quỷ Ám / Âm Khí gây ra (hóa giải tag vàng), chuyển hóa thành 1% Máu mỗi 3 cmt. Tương thích Dị sự: Chống hiệu ứng bất lợi ở Dị sự cấp Ngân và Hoàng. ⚠️ Tác dụng phụ / Lưu ý: Khi bầu khô hút đầy âm khí (sau 3 lần kích hoạt), nó sẽ rung lên lắc lư khiến nhân vật đi loạng choạng, và nó sẽ triệu hồi Lệ Quỷ gần nhất.', 99),
('Tụ Hồn Đăng (Đèn Lồng Gốm Sứ)', 'Trấn vật cứu mạng', 3000, 'AM_DUC', 'Hiếm', '01 chiếc / người',
 'Đèn lồng bằng gốm sứ thắp ngọn nến màu xanh lam, có khả năng níu giữ hồn phách sắp tan biến. Đặt bên cạnh đồng đội vừa gục ngã, tác dụng lên Đồng đội đã hết máu (Đang chờ chết - chỉ dùng được cho tag tím đậm) bằng cách tự động hồi sinh đồng đội đó với 30% Máu (tag đỏ nhạt) mà không cần người khác đến cứu. Tương thích Dị sự: Lật kèo khi toàn đội sắp thua ở Dị sự cấp Phỉ. ⚠️ Tác dụng phụ / Lưu ý: Ngọn đèn cần đủ 5 cmt đốt nến mới hồi sinh xong; nếu trong 5 cmt đó quỷ đến đập vỡ đèn thì đợt hồi sinh sẽ thất bại.', 99),
('Bát Quái Hồi Sinh Trận (Thảm Vải Phong Thủy)', 'Pháp trận cố định', 5500, 'CONG_DUC', 'Hiếm', '01 chiếc / người',
 'Tấm thảm thêu hình âm dương Bát Quái bằng chỉ vàng, tỏa ánh hào quang ấm áp. Trải thảm ra sàn tạo Vùng Cứu Thương bán kính 3m (4 người phạm vi 3m). Tác dụng lên Tất cả đồng đội nằm gục trong vùng, giúp tự động kéo dậy và phục hồi 50% Máu (giảm 1 tag đang chịu) cho toàn bộ người trong thảm sau 4 cmt. Tương thích Dị sự: Cứu vây nhiều đồng đội gục cùng lúc ở Dị sự cấp Hoàng và Phỉ. ⚠️ Tác dụng phụ / Lưu ý: Chiếu Bát Quái phản quang rất mạnh, làm nhòe kính/tầm nhìn của chính đồng đội vừa được cứu dậy trong 2 cmt.', 99);
